### ISSUE TITLE
Search should search for records / ips

### ISSUE THREAD

**Issue by EugenMayer** [tuxis-ie/nsedit#38]
The search should at least search for record names / ips, right-wildcard would be awesome.
Searching for zones is ok, but surely not as useful, or am i wrong? Thanks!

**Comment by harkx** [comment]
Searching for record / ip (and zones of course) would be useful to me.

**Comment by fastcat** [comment]
Obvious use-case for this: find both the A and PTR records for a hostname, to edit both

**Comment by tuxis-ie** [comment]
I thought IU already responded on this one, I guess I didn't, sorry about that.

Yes, it's useful. But it would be even more useful if pdns would allow us to do that. Currently, they don't.  I'll take this up with them, as it would be a cool API feature to have (they already know that, btw). Closing as wonftix, because this should be done at the API.
